name: build
on:
   push:
      branches:
      - main
jobs:
   create-release:
      runs-on: ubuntu-latest
      outputs:
         upload_url: ${{ steps.create-release.outputs.upload_url }}
      steps:
      -  name: Create a release
         id: create-release
         uses: actions/create-release@v1
         env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
            tag_name: ${{ github.ref }}
            release_name: Release
   build-on-windows:
      needs: create-release
      runs-on: windows-latest
      steps:
      -  name: Set up JDK 17
         uses: actions/setup-java@v2
         with:
            distribution: adopt
            java-version: 17
      -  name: Set up Python 3.7
         uses: actions/setup-python@v2
         with:
            python-version: 3.7
            architecture: x64
      -  name: Set up MS Build
         uses: microsoft/setup-msbuild@v1.1
      -  name: Checkout jcef project
         run: |
            export JCEF_DIR="$PWD/src"
            git clone https://github.com/chromiumembedded/java-cef.git $JCEF_DIR
            mkdir -p $JCEF_DIR/jcef_build
         shell: bash
      -  name: Build jcef-win64
         run: |
            set JCEF_DIR="%cd%/src"
            set PYTHON_EXECUTABLE=c:/hostedtoolcache/windows/Python/3.7.9/x64/python.exe
            cd %JCEF_DIR%\jcef_build
            cmake -G "Visual Studio 16" -A x64 ..
            msbuild.exe ALL_BUILD.vcxproj /property:Configuration=Release
            cd ../tools
            call compile.bat win64
            call make_distrib.bat win64
            cd ../binary_distrib/win64/bin
            7z a -tzip -r jcef-win64.zip *
            move jcef-win64.zip ../../../../../
         shell: cmd
      -  name: Upload jcef-win64
         uses: actions/upload-release-asset@v1
         env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
            upload_url: ${{ needs.create-release.outputs.upload_url }}
            asset_path: ./jcef-win64.zip
            asset_name: jcef-win64.zip
            asset_content_type: application/zip
      -  name: Build jcef-win32
         run: |
            set JCEF_DIR="%cd%/src"
            set PYTHON_EXECUTABLE=c:/hostedtoolcache/windows/Python/3.7.9/x64/python.exe
            cd %JCEF_DIR%/jcef_build
            cmake -G "Visual Studio 16" -A Win32 ..
            msbuild.exe ALL_BUILD.vcxproj /property:Configuration=Release
            cd ../tools
            call compile.bat win32
            call make_distrib.bat win32
            cd ../binary_distrib/win32/bin
            7z a -tzip -r jcef-win32.zip *
            move jcef-win32.zip ../../../../../
         shell: cmd
      -  name: Upload jcef-win32
         uses: actions/upload-release-asset@v1
         env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
            upload_url: ${{ needs.create-release.outputs.upload_url }}
            asset_path: ./jcef-win32.zip
            asset_name: jcef-win32.zip
            asset_content_type: application/zip
   build-on-ubuntu:
      needs: create-release
      runs-on: ubuntu-latest
      steps:
      -  name: Set up JDK 17
         uses: actions/setup-java@v2
         with:
            distribution: adopt
            java-version: 17
      -  name: Set up Python 3.7
         uses: actions/setup-python@v2
         with:
            python-version: 3.7
            architecture: x64
      -  name: Set up Clang
         uses: egor-tensin/setup-clang@v1
         with:
            version: latest
            platform: x64
      -  name: Checkout jcef project
         run: |
            export JCEF_DIR="$PWD/src"
            git clone https://github.com/chromiumembedded/java-cef.git $JCEF_DIR
            mkdir -p $JCEF_DIR/jcef_build
         shell: bash
      -  name: Build jcef-linux64
         run: |
            export JCEF_DIR="$PWD/src"
            export PYTHON_EXECUTABLE=/opt/hostedtoolcache/Python/3.7.12/x64/python
            cd $JCEF_DIR/jcef_build
            cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ..
            make -j4
            cd ../tools
            ./compile.sh linux64
            ./make_distrib.sh linux64
            cd ../binary_distrib/linux64/bin
            zip -r jcef-linux64.zip *
            mv jcef-linux64.zip ../../../../../
         shell: bash
      -  name: Upload jcef-linux64
         uses: actions/upload-release-asset@v1
         env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
            upload_url: ${{ needs.create-release.outputs.upload_url }}
            asset_path: ./jcef-linux64.zip
            asset_name: jcef-linux64.zip
            asset_content_type: application/zip
   build-on-macos:
      needs: create-release
      runs-on: macos-latest
      steps:
      -  name: Todo
         run: echo Todo
