name: build
on:
   push:
      branches:
      - main
jobs:
   create-release:
      runs-on: ubuntu-latest
      outputs:
         upload_url: ${{ steps.create_release.outputs.upload_url }}
      steps:
      -  name: Create a release
         id: create_release
         uses: actions/create-release@v1
         env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
            tag_name: ${{ github.ref }}
            release_name: Release ${{ github.ref }}
            draft: true
            prerelease: true
   build-on-windows:
      needs: create-release
      runs-on: windows-latest
      steps:
      -  name: Set up JDK 17
         uses: actions/setup-java@v2
         with:
            distribution: adopt
            java-version: 17
      -  name: Set up Python 3.7
         uses: actions/setup-python@v2
         with:
            python-version: 3.7
            architecture: x64
      -  name: Set up MS Build
         uses: microsoft/setup-msbuild@v1.1
      -  name: Checkout jcef project
         run: |
            export JCEF_DIR="$PWD/src"
            git clone https://github.com/chromiumembedded/java-cef.git $JCEF_DIR
            mkdir -p $JCEF_DIR/jcef_build
         shell: bash
      -  name: Build jcef-win64
         run: |
            set JCEF_DIR="%cd%/src"
            set PYTHON_EXECUTABLE=c:/hostedtoolcache/windows/Python/3.7.9/x64/python.exe
            cd %JCEF_DIR%\jcef_build
            cmake -G "Visual Studio 16" -A x64 ..
            msbuild.exe ALL_BUILD.vcxproj /property:Configuration=Release
            cd ..\tools
            compile.bat win64
            make_distrib.bat win64
         shell: cmd
      -  name: Zip jcef-win64
         uses: thedoctor0/zip-release@master
         with:
            type: zip
            filename: jcef-win64.zip
            directory: src/binary_distrib/win64/bin
      -  name: Build jcef-win32
         run: |
            set JCEF_DIR="%cd%/src"
            set PYTHON_EXECUTABLE=c:/hostedtoolcache/windows/Python/3.7.9/x64/python.exe
            cd %JCEF_DIR%/jcef_build
            cmake -G "Visual Studio 16" -A Win32 ..
            msbuild.exe ALL_BUILD.vcxproj /property:Configuration=Release
            cd ../tools
            compile.bat win32
            make_distrib.bat win32
         shell: cmd
      -  name: Zip jcef-win32
         uses: thedoctor0/zip-release@master
         with:
            type: zip
            filename: jcef-win32.zip
            directory: src/binary_distrib/win32/bin
      -  name: Release
         uses: marvinpinto/action-automatic-releases@latest
         with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            automatic_release_tag: latest
            prerelease: true
            title: Development Build
            files: |-
               src/binary_distrib/win64/bin/jcef-win64.zip
               src/binary_distrib/win64/bin/jcef-win32.zip
   build-on-ubuntu:
      needs: create-release
      runs-on: ubuntu-latest
      steps:
      -  name: Todo
         run: echo Todo
   build-on-macos:
      needs: create-release
      runs-on: macos-latest
      steps:
      -  name: Todo
         run: echo Todo
   rollback-release:
      needs:
      - build-on-windows
      - build-on-ubuntu
      - build-on-macos
      runs-on: ubuntu-latest
      steps:
      -  name: Rollback Release
         if: failure() && steps.create_release.outputs.id != ''
         uses: author/action-rollback@stable
         with:
            id: ${{ steps.create_release.id }}
         env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}