name: build
on:
   push:
      branches:
      - main
jobs:
#
   test:
      runs-on: macos-latest
      steps:
      -  name: Set up JDK 8
         uses: actions/setup-java@v2
         with:
            distribution: zulu
            java-version: 8
            architecture: x64
      -  name: Set up Python 3.7
         uses: actions/setup-python@v2
         with:
            python-version: 3.7
            architecture: x64
      -  uses: seanmiddleditch/gha-setup-ninja@master
      -  name: Checkout jcef project
         run: |
            export JCEF_DIR="$PWD/src"
            git clone https://github.com/chromiumembedded/java-cef.git $JCEF_DIR
            mkdir -p $JCEF_DIR/jcef_build
         shell: bash
      -  name: Setup tmate session
         uses: mxschmitt/action-tmate@v3
#
#
